### ISSUE TITLE
Open Issues old todo list

### ISSUE THREAD

**Issue by ueliwechsler** [ueliwechsler/MPC.jl#1]
- [ ] Port functionality from MPC2 (private)
- [ ]  Discussion: How to add soft-constraint
- [ ] Feature (fancy): Add @controller, @objective, @model macros for the definition of a MPC problem, maybe for the nominal system first
- [ ] Feature: Typing system of AbstractObjective with promote types ond Objective{VN<:, VM<:, etc.}
- [ ] Example: Offsetfree-trakcing MPC07_page32
- [ ] Feature: Soft Constraints and Lagrange multiplier
- [ ]  Feature: Explizit MPC
- [ ] FEATURE: Allow for constraints of successor to be check or not as a global variable
- [ ] Bug: if initial_constraint = :tube, x0 = optimiertes z0 => but this should not be
- [ ] Feature: add input_weight, state_weight method for AbstractObjective to obtain c_x, c_u, Q, R from a objective
- [ ] Feature: Objective for infinity (chebyshev) and 1-norm, see MPC lecture 04_p42
- [ ] Feature: add n-dimensional saturation element 
- [ ] Bug: Figure out why continuous simulation is worse
- [ ] Feature: Incorporate rate constraint better in the structure
- [ ] Example: Example 4.1  from Robust MPC of constrained bounded distrubances
- [ ] Feature: Add basic plot recipe (for series) see case study in https://docs.juliaplots.org/latest/recipes/ 
- [ ]  Feature: Controller with Feedback Linearization
- [ ] Feature: LQI controller
- [ ] Feature: LQR with reference tracking
- [ ] BugFix: Add relaxion of Input and State set according to the error tolerance of the solver!
- [ ] Restructuring: Make eps_abs, eps_rel, max_iter global parameter?
- [ ]  Compare to https://acado.github.io/

Mathematical System:
- [ ] Feature: rand(::AbstractSystem)
- [ ] Documentation: Add Example
- [ ] Feature: Equality Operator
